<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Thinkscape\ActiveRecord\AbstractActiveRecord'                 => __DIR__ . '/src/Thinkscape/ActiveRecord/AbstractActiveRecord.php',
    'Thinkscape\ActiveRecord\Core'                                 => __DIR__ . '/src/Thinkscape/ActiveRecord/Core.php',
    'Thinkscape\ActiveRecord\Exception\BadMethodCallException'     => __DIR__ . '/src/Thinkscape/ActiveRecord/Exception/BadMethodCallException.php',
    'Thinkscape\ActiveRecord\Exception\ExceptionInterface'         => __DIR__ . '/src/Thinkscape/ActiveRecord/Exception/ExceptionInterface.php',
    'Thinkscape\ActiveRecord\Exception\NotFoundException'          => __DIR__ . '/src/Thinkscape/ActiveRecord/Exception/NotFoundException.php',
    'Thinkscape\ActiveRecord\Exception\UndefinedPropertyException' => __DIR__ . '/src/Thinkscape/ActiveRecord/Exception/UndefinedPropertyException.php',
    'Thinkscape\ActiveRecord\Persistence\PersistenceInterface'     => __DIR__ . '/src/Thinkscape/ActiveRecord/Persistence/PersistenceInterface.php',
);
